### PR TITLE
A bunch of stuff

### LINKED ISSUE #10: Test failures on 32 bits arches
On both i686 and armv7hl, one test fails:

```
 /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 /usr/bin/cargo test -j6 -Z avoid-dev-deps --release --no-fail-fast
   Compiling arbitrary v0.2.0 (/builddir/build/BUILD/arbitrary-0.2.0)
     Running `/usr/bin/rustc --crate-name arbitrary src/lib.rs --color never --emit=dep-info,link -C opt-level=3 --test -C metadata=2b9ebc5100c56330 -C extra-filename=-2b9ebc5100c56330 --out-dir /builddir/build/BUILD/arbitrary-0.2.0/target/release/deps -L dependency=/builddir/build/BUILD/arbitrary-0.2.0/target/release/deps -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 --cap-lints=warn`
    Finished release [optimized] target(s) in 5.04s
     Running `/builddir/build/BUILD/arbitrary-0.2.0/target/release/deps/arbitrary-2b9ebc5100c56330`
running 3 tests
test test::finite_buffer_fill_buffer ... ok
test test::ring_buffer_fill_buffer ... ok
test test::ring_buffer_container_size ... FAILED
failures:
---- test::ring_buffer_container_size stdout ----
thread 'test::ring_buffer_container_size' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `9`', src/lib.rs:596:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
    test::ring_buffer_container_size
test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

See build.log on https://koji.fedoraproject.org/koji/taskinfo?taskID=39452113

### LINKED ISSUE #18: "Fill all available space" solution for container size
Broadly, there are two kinds of things Arbitrary generates. Fixed-size objects that map to a fixed set of integers, and variable size objects, which can use something like `container_size()`.

Thing is, unlike, say, quickcheck, we already have a finite number of bytes as input. It would be nice if Arbitrary could be told "hey, I only have X bytes of data and you're my last consumer" as opposed to "slurp as much data as you want, I'll split the difference amongst the next consumers!"

This seems pretty tricky to design in the general case, but we could initially settle for types like `String` and `Vec` just filling directly.

### PR DESCRIPTION
**Pull request by fitzgen**
r? @Manishearth 

This is everything in #19 other than a better `Arbitrary for String` implementation, which I'm not super confident about implementing in a smart way. @Manishearth would you be up for doing that? Or outlining how you think that should be done?

Fixes #10

### CODE REVIEW

File: src/finite_buffer.rs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            }
+            self.offset = max;
+            Ok(())
+        } else {
+            Err(())
+        }
+    }
+
+    // NOTE(blt) I'm not sure if this is the right definition. I don't
+    // understand the purpose of container_size.
```
Comment (Manishearth) [inline src/finite_buffer.rs]: it's supposed to give you a size to use for a container. This would probably change with https://github.com/rust-fuzz/rust_arbitrary/issues/18

File: src/unstructured.rs [hunk 2]
```diff
@@ -64,4 +65,56 @@ impl<'a> Unstructured<'a> {
...
+                inner: self.buffer[offset..].iter().cloned(),
+            })
+        }
+    }
+}
+
+/// An iterator of the remaining bytes returned by
+/// `Unstructured::take_rest`.
+pub struct TakeRest<'a> {
+    inner: iter::Cloned<slice::Iter<'a, u8>>,
```
Comment (Manishearth) [inline src/unstructured.rs]: use `iter::Copied` instead?

File: src/lib.rs [hunk 3]
```diff
@@ -176,15 +176,19 @@ impl_arbitrary_for_floats! {
...
-        const SURROGATES_START: u32 = 0xD800;
-        let mut c = <u32 as Arbitrary>::arbitrary(u)? % CHAR_END;
+
+        // The largest u32 that is a valid unicode character.
+        const CHAR_END: u32 = 0x0011_000 - 1;
+
+        // The size of the surrogate blocks.
+        const SURROGATES_SIZE: u32 = 0xD800;
+
+        let c: u32 = u.int_in_range(0..=CHAR_END)?;
```
Comment (Manishearth) [inline src/lib.rs]: I'm not sure if we should do this, this seems slower.

Comment (Manishearth) [reply src/lib.rs]: Also, the older method slurps up chars as utf32, this will slurp them up as basically utf24 (not a thing that actually exists). The high byte in UTF32 is always null. This seems weird. If we want chars to parse as variable length we should attempt to parse them as utf8 instead.

File: src/unstructured.rs [hunk 4]
```diff
@@ -44,11 +44,23 @@ impl<'a> Unstructured<'a> {
...
+            Some(0) => {
+                self.data = &[];
+                return Ok(0);
+            }
+            Some(max_size) => {
+                // Take lengths from the end of the data, since the `libFuzzer` folks
+                // found that this lets fuzzers more efficiently explore the input
+                // space.
+                //
+                // https://github.com/rust-fuzz/libfuzzer-sys/blob/0c450753/libfuzzer/utils/FuzzedDataProvider.h#L92-L97
```
Comment (Manishearth) [inline src/unstructured.rs]: this is cool

File: src/finite_buffer.rs (hunk 1 above)
Comment (fitzgen) [reply src/finite_buffer.rs]: That was just code motion of an existing comment, FWIW.

File: src/unstructured.rs (hunk 2 above)
Comment (fitzgen) [reply src/unstructured.rs]: I think I will actually remove `TakeRest` and just return the rest of the slice directly -- sound good?

File: src/lib.rs (hunk 3 above)
Comment (fitzgen) [reply src/lib.rs]: Sounds good, will revert this commit.

**Comment by Manishearth** [comment]
That works
